Repository apache/maven-invoker, pull requests merged in 2024-05, with the labels that each got.

#74 [MSHARED-1382] support a possibility to disable snapshots update.
  src/main/java/org/apache/maven/shared/invoker/DefaultInvocationRequest.java
  src/main/java/org/apache/maven/shared/invoker/InvocationRequest.java
  src/main/java/org/apache/maven/shared/invoker/MavenCommandLineBuilder.java
  src/main/java/org/apache/maven/shared/invoker/UpdateSnapshotsPolicy.java
  src/test/java/org/apache/maven/shared/invoker/MavenCommandLineBuilderTest.java
Labels: enhancement

#75 [MSHARED-1389] Refresh download page
  src/site/apt/usage.apt.vm
  src/site/site.xml
  src/site/xdoc/download.xml.vm
Labels: maintenance

#76 [MSHARED-1390] Deprecate InvocationRequest#setGoals
  pom.xml
  src/main/java/org/apache/maven/shared/invoker/DefaultInvocationRequest.java
  src/main/java/org/apache/maven/shared/invoker/InvocationRequest.java
  src/main/java/org/apache/maven/shared/invoker/MavenCommandLineBuilder.java
  src/test/java/org/apache/maven/shared/invoker/DefaultInvokerTest.java
  src/test/java/org/apache/maven/shared/invoker/MavenCommandLineBuilderTest.java
Labels: enhancement

#78 [MSHARED-1391] Code cleanups
  src/main/java/org/apache/maven/shared/invoker/MavenCommandLineBuilder.java
  src/test/java/org/apache/maven/shared/invoker/DefaultInvokerTest.java
  src/test/java/org/apache/maven/shared/invoker/MavenCommandLineBuilderTest.java
Labels: maintenance

#77 [MSHARED-1152] Remove public modifier for JUnit5 tests
  pom.xml
  src/test/java/org/apache/maven/shared/invoker/DefaultInvokerTest.java
  src/test/java/org/apache/maven/shared/invoker/MavenCommandLineBuilderTest.java
  src/test/java/org/apache/maven/shared/invoker/SystemOutHandlerTest.java
  src/test/java/org/apache/maven/shared/invoker/SystemOutLoggerTest.java
Labels: maintenance

#79 [MSHARED-971] Add test for inherited environment
  pom.xml
  src/test/java/org/apache/maven/shared/invoker/DefaultInvokerTest.java
  src/test/resources/not-inherit-env-variables/pom.xml
Labels: bug
